# Generated by Django 5.1.6 on 2025-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.FloatField(default=0.0)),
                ('num_review', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.CharField(default='Unknown', max_length=50)),
                ('destination', models.CharField(default='Unknown', max_length=50)),
                ('short_description', models.TextField(default='No short description available')),
                ('long_description', models.TextField(default='No long description available')),
                ('highlights', models.TextField(default='No highlights specified')),
                ('itinerary', models.TextField(default='No itinerary specified')),
                ('inclusions', models.TextField(default='No inclusions specified')),
                ('exclusions', models.TextField(default='No exclusions specified')),
                ('customers', models.ManyToManyField(related_name='packages', through='booking.Booking', to='customer.customer')),
            ],
        ),
    ]
