# Generated by Django 5.1.6 on 2025-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(upload_to='packages/'),
        ),
    ]
