# Generated by Django 5.1.6 on 2025-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packages_options_packages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
