# Generated by Django 5.1.6 on 2025-04-01 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_packages_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='hero_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hero_images/'),
            preserve_default=False,
        ),
    ]
