# Generated by Django 5.1.6 on 2025-04-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_itineraryday_itineraryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitem',
            name='day',
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
        migrations.DeleteModel(
            name='ItineraryItem',
        ),
    ]
